name: yolo-auto-backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - fastapi==0.111.0
    - uvicorn[standard]==0.29.0
    - sqlalchemy==2.0.30
    - alembic==1.13.1
    - python-dotenv==1.0.1
    - pytest==8.2.2
    - ruff==0.4.4
