"""Simplify YoloVersion model and remove YoloModule

Revision ID: ae550bdd2f77
Revises: d34b491ac907
Create Date: 2025-06-26 01:54:54.120139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'ae550bdd2f77'
down_revision: Union[str, None] = 'd34b491ac907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yolomodule_id'), table_name='yolomodule')
    op.drop_index(op.f('ix_yolomodule_module_type'), table_name='yolomodule')
    op.drop_index(op.f('ix_yolomodule_name'), table_name='yolomodule')
    op.drop_table('yolomodule')
    op.add_column('yoloversion', sa.Column('description', sa.String(), nullable=True))
    op.add_column('yoloversion', sa.Column('architecture', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_yoloversion_name'), table_name='yoloversion')
    op.create_index(op.f('ix_yoloversion_name'), 'yoloversion', ['name'], unique=True)
    op.drop_column('yoloversion', 'config_schema')
    op.drop_column('yoloversion', 'repo_url')
    op.drop_column('yoloversion', 'performance_metrics')
    op.drop_column('yoloversion', 'default_input_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yoloversion', sa.Column('default_input_size', sa.VARCHAR(), nullable=True))
    op.add_column('yoloversion', sa.Column('performance_metrics', sqlite.JSON(), nullable=True))
    op.add_column('yoloversion', sa.Column('repo_url', sa.VARCHAR(), nullable=True))
    op.add_column('yoloversion', sa.Column('config_schema', sqlite.JSON(), nullable=True))
    op.drop_index(op.f('ix_yoloversion_name'), table_name='yoloversion')
    op.create_index(op.f('ix_yoloversion_name'), 'yoloversion', ['name'], unique=False)
    op.drop_column('yoloversion', 'architecture')
    op.drop_column('yoloversion', 'description')
    op.create_table('yolomodule',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('module_type', sa.VARCHAR(), nullable=False),
    sa.Column('config_path', sa.VARCHAR(), nullable=True),
    sa.Column('yolo_version_id', sa.INTEGER(), nullable=True),
    sa.Column('default_input_size', sa.VARCHAR(), nullable=True),
    sa.Column('performance_metrics', sqlite.JSON(), nullable=True),
    sa.Column('config_schema', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['yolo_version_id'], ['yoloversion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yolomodule_name'), 'yolomodule', ['name'], unique=False)
    op.create_index(op.f('ix_yolomodule_module_type'), 'yolomodule', ['module_type'], unique=False)
    op.create_index(op.f('ix_yolomodule_id'), 'yolomodule', ['id'], unique=False)
    # ### end Alembic commands ###
