"""Remove paper_url from YoloVersion

Revision ID: d34b491ac907
Revises: f528b38a6f06
Create Date: 2025-06-26 01:28:48.496310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd34b491ac907'
down_revision: Union[str, None] = 'f528b38a6f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yoloversion', 'paper_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yoloversion', sa.Column('paper_url', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
