"""Add YoloModule table and relationship

Revision ID: f528b38a6f06
Revises: a7daccc22ddc
Create Date: 2025-06-26 01:18:14.342804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f528b38a6f06'
down_revision: Union[str, None] = 'a7daccc22ddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yolomodule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('module_type', sa.String(), nullable=False),
    sa.Column('config_path', sa.String(), nullable=True),
    sa.Column('yolo_version_id', sa.Integer(), nullable=True),
    sa.Column('default_input_size', sa.String(), nullable=True),
    sa.Column('performance_metrics', sa.JSON(), nullable=True),
    sa.Column('config_schema', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['yolo_version_id'], ['yoloversion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yolomodule_id'), 'yolomodule', ['id'], unique=False)
    op.create_index(op.f('ix_yolomodule_module_type'), 'yolomodule', ['module_type'], unique=False)
    op.create_index(op.f('ix_yolomodule_name'), 'yolomodule', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yolomodule_name'), table_name='yolomodule')
    op.drop_index(op.f('ix_yolomodule_module_type'), table_name='yolomodule')
    op.drop_index(op.f('ix_yolomodule_id'), table_name='yolomodule')
    op.drop_table('yolomodule')
    # ### end Alembic commands ###
